server:
  port: 8080
  servlet:
    context-path: /

spring:
#    mvc:
#      view:
#        prefix: /WEB-INF/views/
#        suffix: .jsp

    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/blog?serverTimezone=Asia/Seoul
      username: kkot
      password: 1234

    jpa:
      open-in-view: true
      hibernate:
#        ddl-auto: create
        ddl-auto: update
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # Entity 클래스의 필드명을 스네이크(언더스코어) 표기로 변환
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Entity 클래스의 필드명 그대로 사용
        use-new-id-generator-mappings: false # JPA 기본 넘버링 전략 사용 여부
#      show-sql: true # 콘솔창에 SQL 표시 여부
      show-sql: false
      properties:
        hibernate.format_sql: true

    jackson:
      serialization:
        fail-on-empty-beans: false

    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

# OAuth2 인증 회원용 비밀번호
kkot:
  key: 1234